// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQQyzkIditILpeSpzpfSFj41RUbDYWFo',
    appId: '1:676907295918:web:24d582057d9003d035393f',
    messagingSenderId: '676907295918',
    projectId: 'newsapp-28053',
    authDomain: 'newsapp-28053.firebaseapp.com',
    storageBucket: 'newsapp-28053.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDovsTHoICKgQB6I26VHR5HNF1PVWXjtCo',
    appId: '1:676907295918:android:ea859c99443b91e135393f',
    messagingSenderId: '676907295918',
    projectId: 'newsapp-28053',
    storageBucket: 'newsapp-28053.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHETsU2W4Te0qyPeMhLW_FsueB2D0QG6w',
    appId: '1:676907295918:ios:f1b330732704d04e35393f',
    messagingSenderId: '676907295918',
    projectId: 'newsapp-28053',
    storageBucket: 'newsapp-28053.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHETsU2W4Te0qyPeMhLW_FsueB2D0QG6w',
    appId: '1:676907295918:ios:f1b330732704d04e35393f',
    messagingSenderId: '676907295918',
    projectId: 'newsapp-28053',
    storageBucket: 'newsapp-28053.firebasestorage.app',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkQQyzkIditILpeSpzpfSFj41RUbDYWFo',
    appId: '1:676907295918:web:1cf29443bb358a9835393f',
    messagingSenderId: '676907295918',
    projectId: 'newsapp-28053',
    authDomain: 'newsapp-28053.firebaseapp.com',
    storageBucket: 'newsapp-28053.firebasestorage.app',
  );
}
